THREESCALE-10649: Enable dotenv
3scale/apisonator pull request #358
Opened 2024-01-12 09:14 UTC by lvillen

**JIRA issue**
[THREESCALE-10649](https://issues.redhat.com/browse/THREESCALE-10649)

**What this PR does**
`dotenv` gem has been added to facilitate the use of environment variables at development.

**Verification steps**
Try to run apisonator worker adding the following env variables at your `.env` file: 
```
CONFIG_INTERNAL_API_USER=MY_CONFIG_INTERNAL_API_USER
CONFIG_INTERNAL_API_PASSWORD=MY_CONFIG_INTERNAL_API_PASSWORD
CONFIG_QUEUES_MASTER_NAME=MY_CONFIG_QUEUES_MASTER_NAME
CONFIG_REDIS_PROXY=MY_CONFIG_REDIS_PROXY
```

Confirm that the worker runs.

2024-01-15 09:37 UTC, jlledom requested changes
Just a small request, everything else LGTM

2024-01-15 09:37 UTC, jlledom commented on .env.template
> +CONFIG_FILE=./openshift/3scale_backend.conf
I found there's a `openshift/env.test` file. I think it's better to use that file as example and remove this one.

`env.test` is being used to provide env vars to the container, check [openshift/README.md](https://github.com/3scale/apisonator/blob/master/openshift/README.md)

2024-01-16 08:40 UTC, jlledom approved these changes

2024-01-16 14:48 UTC, eguzki approved these changes

2024-01-16 15:51 UTC, merged